logo: /images/logo-300px.png
show_downloads: [true to enable ]
theme: jekyll-theme-minimal
show_downloads: true ["true" or "false" to indicate whether to provide a download URL]
google_analytics: UA-38078236-9
url: https://caffeinated.training
baseurl: ""

gem "github-pages", group: :jekyll_plugins

include: 
  - _redirects
  
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  - s3_website.yml
  
github: [metadata]
repository: caffeinated.training/OilSlick