title: Oil Slick Coffee Training Material
theme: jekyll-theme-minimal
show_downloads: true ["true" or "false" to indicate whether to provide a download URL]
google_analytics: UA-38078236-9

gem "github-pages", group: :jekyll_plugins
